### ISSUE TITLE
ETCD install fails due to broken update to etcd container.

### ISSUE THREAD

**Issue by sbobovich** [supergiant/supergiant-cli#10]

**Comment by gopherstein** [comment]
```					Containers: []*guber.Container{
						&guber.Container{
							Name:  "etcd",
							Image: "quay.io/coreos/etcd:latest",
							VolumeMounts: []*guber.VolumeMount{
								&guber.VolumeMount{
									Name:      "data",
									MountPath: "/data",
								},
							},```

**Comment by gopherstein** [comment]
`					Containers: []*guber.Container{
						&guber.Container{
							Name:  "etcd",
							Image: "quay.io/coreos/etcd:latest",
							VolumeMounts: []*guber.VolumeMount{
								&guber.VolumeMount{
									Name:      "data",
									MountPath: "/data",
								},
							},`

**Comment by gopherstein** [comment]
etcdctl is pulling latest which is broken atm. Setting this to default to the latest stable 2.X version.

**Comment by gopherstein** [comment]
I will also include a etcd validation in this change.

**Comment by gopherstein** [comment]
98050d0286c67ecf7053aeff1abcd041a8ac643a
